{{- if eq .Values.mode "impersonate" -}}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "ssh-gateway.serviceAccountName" . }}
  labels:
    {{- include "ssh-gateway.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-admin
subjects:
- kind: ServiceAccount
  name: {{ include "ssh-gateway.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}
{{- end }}
