---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "ssh-gateway.fullname" . }}-scripts
  labels:
    {{- include "ssh-gateway.labels" . | nindent 4 }}
data:
{{ $currentScope := . }}
{{ range $path, $_ :=  .Files.Glob  "files/bin/*" }}
{{ regexReplaceAll ".*/([^/]*)" $path "${1}" | indent 2 }}: |
{{ $.Files.Get $path | indent 4 }}

{{ end }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "ssh-gateway.fullname" . }}-config
  labels:
    {{- include "ssh-gateway.labels" . | nindent 4 }}
data:
{{ $currentScope := . }}
{{ range $path, $_ :=  .Files.Glob  "files/config/*" }}
{{ regexReplaceAll ".*/([^/]*)" $path "${1}" | indent 2 }}: |
{{ tpl ($.Files.Get $path) $currentScope | indent 4 }}

{{ end }}



