apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "ssh-gateway.fullname" . }}
  annotations:
    checksum/config-sshd: {{ $.Files.Get "files/bin/sshd.sh" | sha256sum }}
    checksum/config-authorized_keys: {{ $.Files.Get "files/bin/authorized_keys.sh" | sha256sum }}
    checksum/config-authorized_keys: {{ tpl ($.Files.Get "files/config/sshd_config") . | sha256sum }}
  labels:
    {{- include "ssh-gateway.labels" . | nindent 4 }}
spec:
{{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
{{- end }}
  selector:
    matchLabels:
      {{- include "ssh-gateway.selectorLabels" . | nindent 6 }}
  template:
    metadata:
    {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      labels:
        {{- include "ssh-gateway.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "ssh-gateway.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:

        - name: ssh-gateway
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          command: [ "/ssh-gateway" ]
          ports:
            - name: ssh
              containerPort: {{ .Values.service.port }}
              protocol: TCP
              {{ if .Values.service.hostPort }}
              hostPort: {{ .Values.service.port }}
              {{ end }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}

      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
