apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ include "ssh-gateway.fullname" . }}
  labels:
    {{- include "ssh-gateway.labels" . | nindent 4 }}
spec:
  podSelector:
    matchLabels:
      {{- include "ssh-gateway.labels" . | nindent 6 }}
  policyTypes:
  - Ingress
  - Egress
  ingress:
  - ports:
    - protocol: TCP
      port: {{ .Values.service.port }}
    from: []
  egress:
  - to:
    - namespaceSelector: {}
      podSelector:
        matchLabels:
          component: kube-apiserver
          tier: control-plane
    ports:
    - protocol: TCP
      port: 6443
    - protocol: TCP
      port: 443
