{{- if .Values.serviceAccount.create -}}
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "ssh-gateway.serviceAccountName" . }}
  labels:
    {{- include "ssh-gateway.labels" . | nindent 4 }}
subjects:
- kind: ServiceAccount
  name: {{ include "ssh-gateway.serviceAccountName" . }}
roleRef:
  kind: Role
  name: {{ include "ssh-gateway.serviceAccountName" . }}
  apiGroup: rbac.authorization.k8s.io  
  
{{- end }}
