---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ include "ssh-gateway.serviceAccountName" . }}
  labels:
    {{- include "ssh-gateway.labels" . | nindent 4 }}
rules:
{{ $mode := default "impersonate" .Values.mode }}
{{ if eq $mode "serviceaccounts" }}
- apiGroups: [""]
  resources: ["serviceaccounts"]
  verbs: ["get"]
- apiGroups: [""]
  resources: ["secrets"]
  verbs: ["get"]
{{ else }}{{ if eq $mode "proxy" }}
- apiGroups: [""]
  resources: [ "{{ default "serviceaccounts" .Values.resourceType }}" ]
  verbs: ["get"]
{{ else }}
- apiGroups: [""]
  resources: [ "{{ default "serviceaccounts"  .Values.resourceType }}" ]
  verbs: ["get"]
{{ end }}
- apiGroups: [""]
  resources: ["secrets"]
  resourceNames: [ "{{ default (include "ssh-gateway.fullname" .) .Values.secretName }}" ]
  verbs: [ "get", "list", "watch", "create", "update", "patch", "delete" ]
{{- end }}
