{{ if .Values.userCRD.create }}
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: users.{{ .Values.userCRD.apiGroup }}
  labels:
    {{- include "ssh-gateway.labels" . | nindent 4 }}
spec:
  group: {{ .Values.userCRD.apiGroup }}
  versions:
    - name: v1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties: {}
  scope: Namespaced
  names:
    plural: users
    singular: user
    kind: User
    shortNames:
    - user
    - usr
{{ end }}
